### ISSUE TITLE
修改的图标，重启手机之后会变白图标

### ISSUE THREAD

**Issue by LaoYuan77** [huami1314/SuperIcons#10]
下午改了俩软件的图标，其中一个砸壳IPA文件，利用的轻松签+修改的，另外一个是App Store安装的软件，利用SuperIcons修改的，通过巨魔重建图标缓存之后，图标都改成了我替换的，但是重启手机之后轻松签+修改过的图标依旧正常，但是SuperIcons修改过的图标却成了白图标，无奈只好换回了原图标。

PS:手机是12PM，iOS 14.3，巨魔1代   1.5.1版本

**Comment by huami1314** [comment]
14系统...emm

**Comment by huami1314** [comment]
确实如此 但在重建图标缓存后可恢复

**Comment by LaoYuan77** [comment]
虽然再次重建缓存确实可以变回改的图标，但是当你再次重启手机之后还是会变回白图标

**Comment by LaoYuan77** [comment]
所以只能迫于无奈 改回原图标 而且还要再次重建图标 才能从白图标变回原图标 有点繁琐

**Comment by huami1314** [comment]
确实找不到有什么解决方案...
