### ISSUE TITLE
把我原来的图标改没了

### ISSUE THREAD

**Issue by 2666w** [huami1314/SuperIcons#11]
并未修改图标，按的取消
图一是APP的目前看到的图标
![image](https://github.com/user-attachments/assets/7c26f509-8e4a-4656-a308-9b12ec0c0062)
图二是还原错误
![image](https://github.com/user-attachments/assets/a4f2f0fa-a469-4069-af96-dadd7e86da4e)

关机重启过，图标还是无法还原成原来的

**Comment by BlackSpacee** [comment]
我也遇到了，重装解决了

**Comment by huami1314** [comment]
重新安装，更新都可以解决。
或 重建图标缓存
